### ISSUE TITLE
detect similarities between two faces  

### ISSUE THREAD

**Issue by thecodermaniac** [thecodermaniac/FaceApi#10]
### Functionality details
1. add an api endpoint which is able to compare similarities between two faces.
2.  May use tensorflow ml models for the task or import other 3rd party models
3.  **Optional** return the bounding box coordinates along with probability of the determing the face 

### Usage
1.  will be used when needed to verify the person signing up or logging in. 

### Reference:- face <a href="https://medium.com/@gowtham180502/how-to-compare-two-images-and-get-an-accuracy-level-with-python-61d8d953a942#:~:text=Comparing%20would%20be%20done%20by,difference%20between%20100%20and%20face_distance."> compare </a>

**Comment by ASHUdev05** [comment]
May I be assigned to this i would like to explore more and contribute (:

**Comment by Zhreyu** [comment]
Hey can I work on this?

**Comment by thecodermaniac** [comment]
> May I be assigned to this i would like to explore more and contribute (:

assigned to you

**Comment by thecodermaniac** [comment]
> Hey can I work on this?

you can work on this issue #9 
if you agree i can assign you that issue

**Comment by ASHUdev05** [comment]
> > May I be assigned to this i would like to explore more and contribute (:
> 
> assigned to you

Can you please add necessary tags for hacktobefest-accepted prs it will be appreciated. I am almost done will add a PR soon!

**Comment by thecodermaniac** [comment]
> > > May I be assigned to this i would like to explore more and contribute (:
> > 
> > 
> > assigned to you
> 
> Can you please add necessary tags for hacktobefest-accepted prs it will be appreciated. I am almost done will add a PR soon!

all the tags are already added 
**hacktoberfest-accepted** tag will be added to the review of your PR
PS: other than that if I have missed something you can write the tags ;)
<a href="https://hacktoberfest.com/participation/#maintainers">Reference</a>

**Comment by ASHUdev05** [comment]
Since this PR is merged can this issue be closed?
